### ISSUE TITLE
Installation nicht möglich

### ISSUE THREAD

**Issue by 100prznt** [100prznt/EzoGateway#32]
> [...] habe mir das Release 0.4.15 geladen und versucht zu installieren. Und da hänge ich gerade und komme nicht weiter. Ich bekomme die Meldung:
" this package depends on a framework that could not be found. Provide the Microsoft.NET.Native.Framework.1.7 with neutral or ARM processor architecture and minimum version 1.7.27413.0"
Ich habe Probleme die Version 1.7 für ARM zu finden. Die meisten haben eine x64 structure. Kannst du mir da aushelfen?

**Comment by 100prznt** [comment]
Add depe

**Comment by 100prznt** [comment]
Vorgehen zum Beheben des o.g. Problems.

1. Die Windows Version auf dem RasperryPi aktualisieren. Dazu im **Device Portal** unter **Windows Update** die Aktualisierung anstoßen. Download und Installation kann mehrere Minuten in Anspruch nehmen, auch der folgende Systemneustart dauert etwas länger. Danach sollte als laufende OS Version min. 10.0.17763.1397 angezeigt werden.
2. Installation der drei im [source/Dependencies/arm](https://github.com/100prznt/EzoGateway/tree/master/source/Dependencies/arm) abgelegten Pakete.
3. Installation des EzoGateway Paketes aus dem [Release Feed](https://github.com/100prznt/EzoGateway/releases)

**Comment by flapman** [comment]
Hat geklappt.

**Comment by 100prznt** [comment]
Hallo @flapman 

das App-Paket wurde nun auf die jüngsten Bibliotheken (Newtonsoft.Json und MS.NETCore.UWP) aktualisiert.


Dennoch ist es erforderlich unter der Windows Version 10.0.17763.x (z.B. 107, ein neueres Bulid bekommen ich aktuell nicht angeboten) die o.g. Pakete nach zu installieren.

Dies geht auch ganz normal über den Apps Manager, in der Reihenfolge:
1.	Microsoft.VCLibs.ARM.14.00.appx
2.	Microsoft.NET.Native.Framework.1.7.appx
3.	Microsoft.NET.Native.Runtime.1.7.appx

Im Anschluss lässt sich das EzoGateway App-Paket installieren, ebenfalls über den Apps Manager.

Zwischen dem Release 0.4.29-beta und 0.4.44-beta gibt es keinen funktionalen Unterschied, ich würde die Verwendung der 0.4.29-beta empfehlen, da diese Version unter realen Anwendungsbedingungen getestet ist. (Für die 0.4.44-beta stehen diese Tests aktuell noch aus.)


Beste Grüße Elias

**Comment by flapman** [comment]
Hat im zweiten Anlauf geklappt. Die Reihenfolge brachte die gleiche Fehlermeldung bei einzeln hinzufügen. Erst nachdem ich mit: Allow me to select framework packages, die Packete zusammen hochgeladen habe ging es.
Danke.
