### ISSUE TITLE
Nach Update, Oberfläche nicht mehr erreichbar

### ISSUE THREAD

**Issue by flapman** [100prznt/EzoGateway#33]
Letzte stable Version war 0.4.15.
Mit 0.4.23 und 0.4.26 ist die Oberfläche nicht erreichbar. Nach downgrade auf 0.4.15 geht es wieder.

**Comment by 100prznt** [comment]
Wenn die Weboberfläche nicht erreichbar ist, ist leider davon auszugehen das die App nicht läuft.

Wenn sich die App erfolgreich ohne Fehlermeldung installieren lassen hat und im App-Manager (Device Portal) auch normal gestartet werden kann, hilft nur ein Blick in die Log-Datei. Der Zugriff erfolgt ohne HTTP-Server allerdings wie folgt, über das Windows Dateisystem:

1. RaspberryPi neu starten, die EzoGateway App sollte zuvor als Default Startapp festgelegt sein, sodass sie automatisch startet
2. Dem System etwas Zeit geben, sodass die App initialisiert werden kann (5 Minuten 🍵 )
3. Windows Device Portal im Browser öffnen und Anmelden
4. Zum Datei Explorer navigieren (Apps ->File explorer)
5. Zum Log Verzeichnis wechseln (LocalAppData -> EzoGateway -> LocalState -> Log)
6. Die jüngste Log Datei lokal speichern.

Grüße Elias

**Comment by flapman** [comment]
`31.08.2020 15:00:10   ;Info          ;App             ;Startup EzoGateway App
31.08.2020 15:00:10   ;Info          ;App             ;Version 0.4.26.0
31.08.2020 15:00:10   ;Info          ;App             ;Initialize built-in GUI
31.08.2020 15:00:10   ;Info          ;App             ;Init EzoGateway controller
31.08.2020 15:00:10   ;Info          ;Configuration   ;Start load config
31.08.2020 15:00:10   ;Info          ;Configuration   ;Start load 1-wire config
31.08.2020 15:00:10   ;Warning       ;Configuration   ;Configuration not found, genarate default config
31.08.2020 15:00:10   ;Info          ;Configuration   ;Start save config
31.08.2020 15:00:10   ;Info          ;Configuration   ;Start delete config
31.08.2020 15:00:10   ;Info          ;HttpServer      ;HTTP server is successfully initialized and listen for http requests under: http://192.168.178.61:80/
31.08.2020 15:00:10   ;Info          ;App             ;
                                                       :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
                                                       :'########:'########::'#######:::'######::::::'###::::'########:'########:'##:::::'##::::'###::::'##:::'##:
                                                       : ##.....::..... ##::'##.... ##:'##... ##::::'## ##:::... ##..:: ##.....:: ##:'##: ##:::'## ##:::. ##:'##::
                                                       : ##::::::::::: ##::: ##:::: ##: ##:::..::::'##:. ##::::: ##:::: ##::::::: ##: ##: ##::'##:. ##:::. ####:::
                                                       : ######:::::: ##:::: ##:::: ##: ##::'####:'##:::. ##:::: ##:::: ######::: ##: ##: ##:'##:::. ##:::. ##::::
                                                       : ##...:::::: ##::::: ##:::: ##: ##::: ##:: #########:::: ##:::: ##...:::: ##: ##: ##: #########:::: ##::::
                                                       : ##:::::::: ##:::::: ##:::: ##: ##::: ##:: ##.... ##:::: ##:::: ##::::::: ##: ##: ##: ##.... ##:::: ##::::
                                                       : ########: ########:. #######::. ######::: ##:::: ##:::: ##:::: ########:. ###. ###:: ##:::: ##:::: ##::::
                                                       :........::........:::.......::::......::::..:::::..:::::..:::::........:::...::...:::..:::::..:::::..:::::
                                                       ...........................................................................................................
                                                       :::::::::::::::::::::::::::::::::::::::::::::: IS NOW RUNNING :::::::::::::::::::::::::::::::::::::::::::::
                                                       
31.08.2020 15:00:10   ;Info          ;Configuration   ;Controller_ConfigIsSavedEvent
31.08.2020 15:00:10   ;Info          ;Logger          ;Logger configuration changed!
31.08.2020 15:00:10   ;Info          ;Logger          ;Logger:                Enabled
31.08.2020 15:00:10   ;Info          ;Logger          ;Excluded sub-systems: None
31.08.2020 15:00:10   ;Info          ;Logger          ;Minimum loglevel:     Info
31.08.2020 15:00:10   ;Info          ;App             ;Start init cyclic updater
31.08.2020 15:00:10   ;Info          ;App             ;Disable cyclic updater.
31.08.2020 15:00:10   ;Info          ;Configuration   ;Controller_ConfigIsLoadedEvent
31.08.2020 15:00:10   ;Info          ;Configuration   ;Configuration JSON (in the following lines)
                                                       {
                                                         "PhSensor": {
                                                           "Enabled": true,
                                                           "I2CAddress": 99
                                                         },
                                                         "RedoxSensor": {
                                                           "Enabled": true,
                                                           "I2CAddress": 98
                                                         },
                                                         "TemperatureSensor": {
                                                           "Enabled": true,
                                                           "I2CAddress": 102
                                                         },
                                                         "EnablePhTemperatureCompensation": true,
                                                         "TemperatureUnit": "Celsius",
                                                         "EnableCyclicUpdater": false,
                                                         "UpdateInterval": 60,
                                                         "LogoConnection": {
                                                           "Enabled": false,
                                                           "IpAddress": "192.168.0.195",
                                                           "TriggerVmAddress": 106,
                                                           "TriggerVmAddressBit": 0,
                                                           "PhVmAddress": 302,
                                                           "RedoxVmAddress": 304,
                                                           "TemperatureVmAddress": 306,
                                                           "SecureCounterVmAddress": 300
                                                         },
                                                         "Appearance": {
                                                           "DeviceName": "EzoGateway"
                                                         },
                                                         "Logger": {
                                                           "Enabled": true,
                                                           "ExcludedSubSystems": 0,
                                                           "MinimumLogLevel": 0,
                                                           "Lifetime": 30
                                                         }
                                                       }
31.08.2020 15:00:10   ;Info          ;LowLevel        ;Start init hardware
31.08.2020 15:00:10   ;Info          ;LowLevel        ;Start initialization of the Atlas Scientific EZO pH Circuit
31.08.2020 15:00:10   ;Warning       ;Configuration   ;1-wire configuration not found, genarate default config
31.08.2020 15:00:10   ;Info          ;Configuration   ;Start save 1-wire config
31.08.2020 15:00:10   ;Info          ;Configuration   ;Start delete config
31.08.2020 15:00:11   ;Info          ;LowLevel        ;Atlas Scientific EZO pH Circuit successfully initialized, FW: 2.14
31.08.2020 15:00:12   ;Info          ;LowLevel        ;Start initialization of the Atlas Scientific EZO ORP circuit
31.08.2020 15:00:12   ;Info          ;LowLevel        ;Atlas Scientific EZO ORP circuit successfully initialized, FW: 2.11
31.08.2020 15:00:13   ;Info          ;LowLevel        ;Start initialization of the Atlas Scientific EZO RTD circuit
31.08.2020 15:00:13   ;Error         ;LowLevel        ;Error during initialization of the Atlas Scientific EZO RTD Circuit, see details below
31.08.2020 15:00:13   ;Error         ;LowLevel        ;The system cannot find the file specified.
                                                       
                                                       Slave address was not acknowledged.
31.08.2020 15:00:13   ;Info          ;LowLevel        ;Hardware successfully initialized.
31.08.2020 15:00:13   ;Info          ;Logger          ;Logger configuration changed!
31.08.2020 15:00:13   ;Info          ;Logger          ;Logger:                Enabled
31.08.2020 15:00:13   ;Info          ;Logger          ;Excluded sub-systems: None
31.08.2020 15:00:13   ;Info          ;Logger          ;Minimum loglevel:     Info
31.08.2020 15:00:13   ;Info          ;App             ;Start init cyclic updater
31.08.2020 15:00:13   ;Info          ;App             ;Disable cyclic updater.
`

**Comment by flapman** [comment]
`31.08.2020 15:00:10   ;Info          ;App             ;Startup EzoGateway App
31.08.2020 15:00:10   ;Info          ;App             ;Version 0.4.26.0
31.08.2020 15:00:10   ;Info          ;App             ;Initialize built-in GUI
31.08.2020 15:00:10   ;Info          ;App             ;Init EzoGateway controller
31.08.2020 15:00:10   ;Info          ;Configuration   ;Start load config
31.08.2020 15:00:10   ;Info          ;Configuration   ;Start load 1-wire config
31.08.2020 15:00:10   ;Warning       ;Configuration   ;Configuration not found, genarate default config
31.08.2020 15:00:10   ;Info          ;Configuration   ;Start save config
31.08.2020 15:00:10   ;Info          ;Configuration   ;Start delete config
31.08.2020 15:00:10   ;Info          ;HttpServer      ;HTTP server is successfully initialized and listen for http requests under: http://19**********1:80/
31.08.2020 15:00:10   ;Info          ;App             ;
                                                       :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
                                                       :'########:'########::'#######:::'######::::::'###::::'########:'########:'##:::::'##::::'###::::'##:::'##:
                                                       : ##.....::..... ##::'##.... ##:'##... ##::::'## ##:::... ##..:: ##.....:: ##:'##: ##:::'## ##:::. ##:'##::
                                                       : ##::::::::::: ##::: ##:::: ##: ##:::..::::'##:. ##::::: ##:::: ##::::::: ##: ##: ##::'##:. ##:::. ####:::
                                                       : ######:::::: ##:::: ##:::: ##: ##::'####:'##:::. ##:::: ##:::: ######::: ##: ##: ##:'##:::. ##:::. ##::::
                                                       : ##...:::::: ##::::: ##:::: ##: ##::: ##:: #########:::: ##:::: ##...:::: ##: ##: ##: #########:::: ##::::
                                                       : ##:::::::: ##:::::: ##:::: ##: ##::: ##:: ##.... ##:::: ##:::: ##::::::: ##: ##: ##: ##.... ##:::: ##::::
                                                       : ########: ########:. #######::. ######::: ##:::: ##:::: ##:::: ########:. ###. ###:: ##:::: ##:::: ##::::
                                                       :........::........:::.......::::......::::..:::::..:::::..:::::........:::...::...:::..:::::..:::::..:::::
                                                       ...........................................................................................................
                                                       :::::::::::::::::::::::::::::::::::::::::::::: IS NOW RUNNING :::::::::::::::::::::::::::::::::::::::::::::
                                                       
31.08.2020 15:00:10   ;Info          ;Configuration   ;Controller_ConfigIsSavedEvent
31.08.2020 15:00:10   ;Info          ;Logger          ;Logger configuration changed!
31.08.2020 15:00:10   ;Info          ;Logger          ;Logger:                Enabled
31.08.2020 15:00:10   ;Info          ;Logger          ;Excluded sub-systems: None
31.08.2020 15:00:10   ;Info          ;Logger          ;Minimum loglevel:     Info
31.08.2020 15:00:10   ;Info          ;App             ;Start init cyclic updater
31.08.2020 15:00:10   ;Info          ;App             ;Disable cyclic updater.
31.08.2020 15:00:10   ;Info          ;Configuration   ;Controller_ConfigIsLoadedEvent
31.08.2020 15:00:10   ;Info          ;Configuration   ;Configuration JSON (in the following lines)
                                                       {
                                                         "PhSensor": {
                                                           "Enabled": true,
                                                           "I2CAddress": 99
                                                         },
                                                         "RedoxSensor": {
                                                           "Enabled": true,
                                                           "I2CAddress": 98
                                                         },
                                                         "TemperatureSensor": {
                                                           "Enabled": true,
                                                           "I2CAddress": 102
                                                         },
                                                         "EnablePhTemperatureCompensation": true,
                                                         "TemperatureUnit": "Celsius",
                                                         "EnableCyclicUpdater": false,
                                                         "UpdateInterval": 60,
                                                         "LogoConnection": {
                                                           "Enabled": false,
                                                           "IpAddress": "192.*********.195",
                                                           "TriggerVmAddress": 106,
                                                           "TriggerVmAddressBit": 0,
                                                           "PhVmAddress": 302,
                                                           "RedoxVmAddress": 304,
                                                           "TemperatureVmAddress": 306,
                                                           "SecureCounterVmAddress": 300
                                                         },
                                                         "Appearance": {
                                                           "DeviceName": "EzoGateway"
                                                         },
                                                         "Logger": {
                                                           "Enabled": true,
                                                           "ExcludedSubSystems": 0,
                                                           "MinimumLogLevel": 0,
                                                           "Lifetime": 30
                                                         }
                                                       }
31.08.2020 15:00:10   ;Info          ;LowLevel        ;Start init hardware
31.08.2020 15:00:10   ;Info          ;LowLevel        ;Start initialization of the Atlas Scientific EZO pH Circuit
31.08.2020 15:00:10   ;Warning       ;Configuration   ;1-wire configuration not found, genarate default config
31.08.2020 15:00:10   ;Info          ;Configuration   ;Start save 1-wire config
31.08.2020 15:00:10   ;Info          ;Configuration   ;Start delete config
31.08.2020 15:00:11   ;Info          ;LowLevel        ;Atlas Scientific EZO pH Circuit successfully initialized, FW: 2.14
31.08.2020 15:00:12   ;Info          ;LowLevel        ;Start initialization of the Atlas Scientific EZO ORP circuit
31.08.2020 15:00:12   ;Info          ;LowLevel        ;Atlas Scientific EZO ORP circuit successfully initialized, FW: 2.11
31.08.2020 15:00:13   ;Info          ;LowLevel        ;Start initialization of the Atlas Scientific EZO RTD circuit
31.08.2020 15:00:13   ;Error         ;LowLevel        ;Error during initialization of the Atlas Scientific EZO RTD Circuit, see details below
31.08.2020 15:00:13   ;Error         ;LowLevel        ;The system cannot find the file specified.
                                                       
                                                       Slave address was not acknowledged.
31.08.2020 15:00:13   ;Info          ;LowLevel        ;Hardware successfully initialized.
31.08.2020 15:00:13   ;Info          ;Logger          ;Logger configuration changed!
31.08.2020 15:00:13   ;Info          ;Logger          ;Logger:                Enabled
31.08.2020 15:00:13   ;Info          ;Logger          ;Excluded sub-systems: None
31.08.2020 15:00:13   ;Info          ;Logger          ;Minimum loglevel:     Info
31.08.2020 15:00:13   ;Info          ;App             ;Start init cyclic updater
31.08.2020 15:00:13   ;Info          ;App             ;Disable cyclic updater.
`

**Comment by flapman** [comment]
Ich habe gerade in der Log gesehen, dass der Port sich auf 80 geändert hat, habe es mit 591 probiert.
Oberfläche ist jetzt erreichbar.

**Comment by 100prznt** [comment]
Ja, das EzoGateway läuft auf Port 80.

Ansonsten scheint alles normal hochzufahren. Die zwei Error Einträge kommen vom nicht verbauten RTD Modul.

**Comment by flapman** [comment]
Dann sollte es in der Anleitung geändert werden, diese verweist auf 591.

**Comment by 100prznt** [comment]
> Dann sollte es in der Anleitung geändert werden, diese verweist auf 591.

Danke für den Hinweis, habe es entsprechend korrigiert.
