### ISSUE TITLE
Alle Module inaktiv

### ISSUE THREAD

**Issue by ZeroQool007** [100prznt/EzoGateway#37]
Hallo, zuerst einmal ein super Projekt weshalb ich mir auch alle Komponenten gekauft habe. Bei der Einrichtung habe ich mich genau nach der Anleitung gehalten, aber in der sensors.html sind alle 3 Module inaktiv. Auf dem PI leuchten alle grün. Eigentl. sollten die doch blau leuchten oder? Bei dem I2C drücke ich doch auf den Button und sobald blau ist lasse ich ihn los?

Danke

Gruß

Nachtrag: Lag am Kommunikationsmodus. 
EZO™ pH Circuit und EZO™ O.R.P. Circuit werden nun erkannt, aber nicht der EZO™ RTD Circuit. Mit dem I2C Dongle bekomme ich auch keine blaue LED angezeigt. Der wechselt von grün in ein gemischtes blau grün und dann wieder auf grün. Tip?

**Comment by 100prznt** [comment]
Hast du den **I2C Toggler** für die EZO™ RTD Circuit entsprechend umgestellt? Zm manuellen Wechsel zwischen UART und I2C wird hier nämlich ein anderes Pinning benötigt.

**Comment by ZeroQool007** [comment]
Du hast Recht. Dachte das wären die gleichen Einstellungen wie bei pH und O.R.P. 

Jetzt funktioniert es! Ich danke dir!

**Comment by 100prznt** [comment]
Das freut mich.

Dann noch viel Spaß.
